---
- name: Red Hat subscription account creds
  include_vars:
    file: rhel_sub.yml

- name: Host registration & repo configuration
  shell: |
    subscription-manager register --username="{{ rhel_sub_account }}" --password="{{ rhel_sub_password }}"
    subscription-manager attach
    subscription-manager refresh
    subscription-manager repos --disable="*" > /dev/null
    yum-config-manager --disable \* > /dev/null
    subscription-manager attach --pool={{ rhel_sub_pool_id }}
    subscription-manager repos \
      --enable="rhel-7-server-rpms" \
      --enable="rhel-7-server-extras-rpms" \
      --enable="rhel-7-server-ose-3.10-rpms" \
      --enable="rhel-7-server-ansible-2.4-rpms" \
      --enable="rhel-7-fast-datapath-rpms" \
      --enable="rh-gluster-3-client-for-rhel-7-server-rpms"

- name: Install base packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - wget
    - git
    - net-tools
    - bind-utils
    - yum-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - python-docker-py
    - skopeo
    - openvswitch

- name: Reboot machine with latest packages
  reboot:
