---
- name: installDependencies
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: removeDocker
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker.io
    - docker-common
    - docker-engine

- name: add docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: /etc/yum.repos.d/docker-{{ docker_edition }}.repo
    owner: root
    group: root

- name: install container-selinux package
  yum:
    name: "http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm"
    state: present
    update_cache: yes

- name: installDocker
  yum:
    name: "{{ docker_package }}"
    update_cache: yes
    state: present
  notify: "start docker"

- name: Install docker for python
  pip:
    name: "docker==2.7.0"
    state: latest
    extra_args: --ignore-installed
